# Generated by Django 5.2.7 on 2025-11-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Granja_Vacas', '0004_eventosanitario_notas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('puesto', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Limpiador', 'Limpiador'), ('Ordeñador', 'Ordeñador'), ('Veterinario', 'Veterinario'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendedor', models.ForeignKey(limit_choices_to={'puesto': 'Vendedor'}, on_delete=django.db.models.deletion.CASCADE, to='app_Granja_Vacas.personal')),
            ],
        ),
    ]
